#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# bar
$HOME/dotfiles/xorg/mybar/target/release/mybar &

# Keyboard
xset r rate 220 40 &
setxkbmap -option caps:escape &
setxkbmap -layout us,pt -option grp:alt_shift_toggle &
xinput set-prop 11 "libinput Natural Scrolling Enabled" 1 &
xinput set-prop 11 "libinput Tapping Enabled" 1 &
xinput set-prop 12 'libinput Accel Speed' -0.6 &

# Lock on idle
xss-lock --transfer-sleep-lock -- xsecurelock &
xautolock -time 10 -locker "systemctl suspend-then-hibernate" &

# Launch apps
flameshot &
picom &
dunst &
gammastep -l 39.77:-8.79 -t 6500:3100 &

# start dwm
exec dwm >/dev/null 2>&1
